# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'vtn_principal.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)

class Ui_lbl_tipo_persona(object):
    def setupUi(self, lbl_tipo_persona):
        if not lbl_tipo_persona.objectName():
            lbl_tipo_persona.setObjectName(u"lbl_tipo_persona")
        lbl_tipo_persona.resize(489, 538)
        lbl_tipo_persona.setSizeIncrement(QSize(2, 2))
        self.centralwidget = QWidget(lbl_tipo_persona)
        self.centralwidget.setObjectName(u"centralwidget")
        self.txt_nombre = QLineEdit(self.centralwidget)
        self.txt_nombre.setObjectName(u"txt_nombre")
        self.txt_nombre.setGeometry(QRect(130, 90, 191, 41))
        self.txt_nombre.setMaxLength(50)
        self.txt_apellido = QLineEdit(self.centralwidget)
        self.txt_apellido.setObjectName(u"txt_apellido")
        self.txt_apellido.setGeometry(QRect(130, 140, 191, 41))
        self.txt_apellido.setMaxLength(50)
        self.lbl_nombre = QLabel(self.centralwidget)
        self.lbl_nombre.setObjectName(u"lbl_nombre")
        self.lbl_nombre.setGeometry(QRect(30, 90, 111, 41))
        self.lbl_nombre.setSizeIncrement(QSize(2, 2))
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.lbl_nombre.setFont(font)
        self.lbl_apellido = QLabel(self.centralwidget)
        self.lbl_apellido.setObjectName(u"lbl_apellido")
        self.lbl_apellido.setGeometry(QRect(30, 140, 101, 41))
        self.lbl_apellido.setFont(font)
        self.btn_guardar = QPushButton(self.centralwidget)
        self.btn_guardar.setObjectName(u"btn_guardar")
        self.btn_guardar.setGeometry(QRect(170, 460, 111, 41))
        font1 = QFont()
        font1.setFamilies([u"Myanmar Text"])
        font1.setPointSize(12)
        self.btn_guardar.setFont(font1)
        self.cb_tipo_persona = QComboBox(self.centralwidget)
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.addItem("")
        self.cb_tipo_persona.setObjectName(u"cb_tipo_persona")
        self.cb_tipo_persona.setGeometry(QRect(130, 30, 191, 41))
        self.lbl_tipo_persona_2 = QLabel(self.centralwidget)
        self.lbl_tipo_persona_2.setObjectName(u"lbl_tipo_persona_2")
        self.lbl_tipo_persona_2.setGeometry(QRect(30, 30, 111, 41))
        self.lbl_tipo_persona_2.setSizeIncrement(QSize(2, 2))
        self.lbl_tipo_persona_2.setFont(font)
        self.lbl_email = QLabel(self.centralwidget)
        self.lbl_email.setObjectName(u"lbl_email")
        self.lbl_email.setGeometry(QRect(30, 250, 111, 41))
        self.lbl_email.setSizeIncrement(QSize(2, 2))
        self.lbl_email.setFont(font)
        self.txt_cedula = QLineEdit(self.centralwidget)
        self.txt_cedula.setObjectName(u"txt_cedula")
        self.txt_cedula.setGeometry(QRect(130, 190, 191, 41))
        self.txt_cedula.setMaxLength(13)
        self.txt_email = QLineEdit(self.centralwidget)
        self.txt_email.setObjectName(u"txt_email")
        self.txt_email.setGeometry(QRect(130, 250, 191, 41))
        self.txt_email.setMaxLength(100)
        self.lbl_cedula = QLabel(self.centralwidget)
        self.lbl_cedula.setObjectName(u"lbl_cedula")
        self.lbl_cedula.setGeometry(QRect(30, 190, 101, 41))
        self.lbl_cedula.setFont(font)
        self.lbl_carrera = QLabel(self.centralwidget)
        self.lbl_carrera.setObjectName(u"lbl_carrera")
        self.lbl_carrera.setGeometry(QRect(30, 300, 111, 41))
        self.lbl_carrera.setSizeIncrement(QSize(2, 2))
        self.lbl_carrera.setFont(font)
        self.txt_carrera = QLineEdit(self.centralwidget)
        self.txt_carrera.setObjectName(u"txt_carrera")
        self.txt_carrera.setGeometry(QRect(130, 300, 191, 41))
        self.seleccionar_por_cedula = QPushButton(self.centralwidget)
        self.seleccionar_por_cedula.setObjectName(u"seleccionar_por_cedula")
        self.seleccionar_por_cedula.setGeometry(QRect(330, 200, 151, 21))
        self.lbl_estatura = QLabel(self.centralwidget)
        self.lbl_estatura.setObjectName(u"lbl_estatura")
        self.lbl_estatura.setGeometry(QRect(40, 360, 121, 31))
        self.lbl_estatura.setSizeIncrement(QSize(2, 2))
        self.lbl_estatura.setFont(font)
        self.sp_estatura = QSpinBox(self.centralwidget)
        self.sp_estatura.setObjectName(u"sp_estatura")
        self.sp_estatura.setGeometry(QRect(190, 360, 42, 22))
        self.sp_estatura.setMaximum(300)
        self.btn_estatura = QPushButton(self.centralwidget)
        self.btn_estatura.setObjectName(u"btn_estatura")
        self.btn_estatura.setGeometry(QRect(240, 360, 75, 23))
        self.lbl_peso = QLabel(self.centralwidget)
        self.lbl_peso.setObjectName(u"lbl_peso")
        self.lbl_peso.setGeometry(QRect(80, 380, 161, 31))
        self.lbl_peso.setSizeIncrement(QSize(2, 2))
        self.lbl_peso.setFont(font)
        self.sp_peso = QSpinBox(self.centralwidget)
        self.sp_peso.setObjectName(u"sp_peso")
        self.sp_peso.setGeometry(QRect(190, 390, 42, 22))
        self.sp_peso.setMaximum(300)
        self.btn_peso = QPushButton(self.centralwidget)
        self.btn_peso.setObjectName(u"btn_peso")
        self.btn_peso.setGeometry(QRect(240, 390, 75, 23))
        self.lbl_fecha_nacimiento = QLabel(self.centralwidget)
        self.lbl_fecha_nacimiento.setObjectName(u"lbl_fecha_nacimiento")
        self.lbl_fecha_nacimiento.setGeometry(QRect(30, 420, 181, 21))
        self.lbl_fecha_nacimiento.setSizeIncrement(QSize(2, 2))
        self.lbl_fecha_nacimiento.setFont(font)
        self.btn_fecha_nacimiento = QPushButton(self.centralwidget)
        self.btn_fecha_nacimiento.setObjectName(u"btn_fecha_nacimiento")
        self.btn_fecha_nacimiento.setGeometry(QRect(330, 420, 131, 23))
        self.dateEdit_fecha_nacimiento = QDateEdit(self.centralwidget)
        self.dateEdit_fecha_nacimiento.setObjectName(u"dateEdit_fecha_nacimiento")
        self.dateEdit_fecha_nacimiento.setGeometry(QRect(220, 420, 110, 22))
        lbl_tipo_persona.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(lbl_tipo_persona)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 489, 21))
        lbl_tipo_persona.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(lbl_tipo_persona)
        self.statusbar.setObjectName(u"statusbar")
        lbl_tipo_persona.setStatusBar(self.statusbar)

        self.retranslateUi(lbl_tipo_persona)

        QMetaObject.connectSlotsByName(lbl_tipo_persona)
    # setupUi

    def retranslateUi(self, lbl_tipo_persona):
        lbl_tipo_persona.setWindowTitle(QCoreApplication.translate("lbl_tipo_persona", u"Ventana Principal", None))
        self.lbl_nombre.setText(QCoreApplication.translate("lbl_tipo_persona", u"NOMBRE", None))
        self.lbl_apellido.setText(QCoreApplication.translate("lbl_tipo_persona", u"APELLIDO", None))
        self.btn_guardar.setText(QCoreApplication.translate("lbl_tipo_persona", u"GUARDAR", None))
        self.cb_tipo_persona.setItemText(0, QCoreApplication.translate("lbl_tipo_persona", u"Docente", None))
        self.cb_tipo_persona.setItemText(1, QCoreApplication.translate("lbl_tipo_persona", u"Estudiante", None))

        self.lbl_tipo_persona_2.setText(QCoreApplication.translate("lbl_tipo_persona", u"TIPO", None))
        self.lbl_email.setText(QCoreApplication.translate("lbl_tipo_persona", u"EMAIL", None))
        self.lbl_cedula.setText(QCoreApplication.translate("lbl_tipo_persona", u"CEDULA", None))
        self.lbl_carrera.setText(QCoreApplication.translate("lbl_tipo_persona", u"CARRERA", None))
        self.seleccionar_por_cedula.setText(QCoreApplication.translate("lbl_tipo_persona", u"SELECCIONAR CEDULA", None))
        self.lbl_estatura.setText(QCoreApplication.translate("lbl_tipo_persona", u"ESTATURA(cm):", None))
        self.btn_estatura.setText(QCoreApplication.translate("lbl_tipo_persona", u"E.D Estatura", None))
        self.lbl_peso.setText(QCoreApplication.translate("lbl_tipo_persona", u"PESO(kg):", None))
        self.btn_peso.setText(QCoreApplication.translate("lbl_tipo_persona", u"E.D Peso", None))
        self.lbl_fecha_nacimiento.setText(QCoreApplication.translate("lbl_tipo_persona", u"FECHA DE NACIMIENTO:", None))
        self.btn_fecha_nacimiento.setText(QCoreApplication.translate("lbl_tipo_persona", u"E.D Fecha_nacimiento", None))
    # retranslateUi

